import java.io.IOException
import java.util.*

fun main(){
    val sc = Scanner(System.`in`)
//    try {
//        print("숫자만 입력해라 휴면: ")
//        var x = sc.nextInt()
//        print("너가 친 숫자는 : " + x + "이구나\n")
//    } catch (e: Exception) {
//        print("뭐 잘못침?\n")
//    }


}